In [1]:

import pandas as pd

In [2]:
#print data
data=pd.read_csv("C:/Users/Admin/Downloads/Heart.csv")
data

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [3]:
#delete unnamed column
df=data.iloc[:,1:]
df

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [5]:
#datatype of each column
print("datatypes of each column: ")
dt=df.dtypes
print(dt)
print(" ")

datatypes of each column:
Age            int64
Sex            int64
ChestPain     object
RestBP         int64
Chol           int64
Fbs            int64
RestECG        int64
MaxHR          int64
ExAng          int64
Oldpeak      float64
Slope          int64
Ca           float64
Thal          object
AHD           object
dtype: object

In [6]:
#mean of age column
avg=df['Age'].mean()
avg

54.43894389438944

In [7]:
#null values print
miss=df.isnull()
miss

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [8]:
#null values 
missing=pd.isnull(df).sum()
print("missing values")
print(missing)

missing values
Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         2
AHD          0
dtype: int64

In [9]:
#shape of dataframe
shape = df.shape
print("shape: ",shape)

shape:  (303, 14)

In [10]:
#number of zero 
df1=df[df==0]
df1.count()

Age            0
Sex           97
ChestPain      0
RestBP         0
Chol           0
Fbs          258
RestECG      151
MaxHR          0
ExAng        204
Oldpeak       99
Slope          0
Ca           176
Thal           0
AHD            0
dtype: int64

In [11]:
#6 columns
data3=df[['Age','Sex','ChestPain','RestBP','Chol']]
print(data3)

     Age  Sex     ChestPain  RestBP  Chol
0     63    1       typical     145   233
1     67    1  asymptomatic     160   286
2     67    1  asymptomatic     120   229
3     37    1    nonanginal     130   250
4     41    0    nontypical     130   204
..   ...  ...           ...     ...   ...
298   45    1       typical     110   264
299   68    1  asymptomatic     144   193
300   57    1  asymptomatic     130   131
301   57    0    nontypical     130   236
302   38    1    nonanginal     138   175

[303 rows x 5 columns]

In [12]:
#75% and 25%  of dataframe
div75=df.sample(frac=0.75)
remaindata=df.drop(div75.index)
print("75% data=\n",div75)
print("25% data=\n",remaindata)

75% data=
      Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  \
82    39    1    nonanginal     140   321    0        2    182      0
84    52    1    nontypical     120   325    0        0    172      0
279   58    0  asymptomatic     130   197    0        0    131      0
28    43    1  asymptomatic     150   247    0        0    171      0
283   35    1    nontypical     122   192    0        0    174      0
..   ...  ...           ...     ...   ...  ...      ...    ...    ...
244   60    0    nonanginal     120   178    1        0     96      0
254   43    1  asymptomatic     115   303    0        0    181      0
230   52    0    nonanginal     136   196    0        2    169      0
218   64    0  asymptomatic     130   303    0        0    122      0
161   77    1  asymptomatic     125   304    0        2    162      1

     Oldpeak  Slope   Ca    Thal  AHD
82       0.0      1  0.0  normal   No
84       0.2      1  0.0  normal   No
279      0.6      2  0.0  normal   No
28       1.5      1  0.0  normal   No
283      0.0      1  0.0  normal   No
..       ...    ...  ...     ...  ...
244      0.0      1  0.0  normal   No
254      1.2      2  0.0  normal   No
230      0.1      2  0.0  normal   No
218      2.0      2  2.0  normal   No
161      0.0      1  3.0  normal  Yes

[227 rows x 14 columns]
25% data=
      Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  \
13    44    1    nontypical     120   263    0        0    173      0
16    48    1    nontypical     110   229    0        0    168      0
26    58    0    nonanginal     120   340    0        0    172      0
27    66    0       typical     150   226    0        0    114      0
35    42    1  asymptomatic     140   226    0        0    178      0
..   ...  ...           ...     ...   ...  ...      ...    ...    ...
284   61    1  asymptomatic     148   203    0        0    161      0
295   41    1    nontypical     120   157    0        0    182      0
296   59    1  asymptomatic     164   176    1        2     90      0
297   57    0  asymptomatic     140   241    0        0    123      1
298   45    1       typical     110   264    0        0    132      0

     Oldpeak  Slope   Ca        Thal  AHD
13       0.0      1  0.0  reversable   No
16       1.0      3  0.0  reversable  Yes
26       0.0      1  0.0      normal   No
27       2.6      3  0.0      normal   No
35       0.0      1  0.0      normal   No
..       ...    ...  ...         ...  ...
284      0.0      1  1.0  reversable  Yes
295      0.0      1  0.0      normal   No
296      1.0      2  2.0       fixed  Yes
297      0.2      2  0.0  reversable  Yes
298      1.2      2  0.0  reversable  Yes

[76 rows x 14 columns]

In [13]:
#75 and 25 % of 6 columns
from sklearn.model_selection import train_test_split
x=df.iloc[:,:5]
y=df.iloc[:,13]
X_train,X_test,Y_train,Y_test=train_test_split(x,y,train_size=0.75,test_size=0.25)
X_train

     Age  Sex     ChestPain  RestBP  Chol
261   58    0    nontypical     136   319
194   68    0    nonanginal     120   211
37    57    1  asymptomatic     150   276
72    62    1  asymptomatic     120   267
240   41    1    nontypical     110   235
..   ...  ...           ...     ...   ...
294   63    0  asymptomatic     124   197
202   57    1    nonanginal     150   126
26    58    0    nonanginal     120   340
138   35    1  asymptomatic     120   198
174   64    1  asymptomatic     145   212

[227 rows x 5 columns]

In [14]:
Y_train

261    Yes
194     No
37     Yes
72     Yes
240     No
      ...
294    Yes
202     No
26      No
138    Yes
174    Yes
Name: AHD, Length: 227, dtype: object

In [15]:
X_test

     Age  Sex     ChestPain  RestBP  Chol
302   38    1    nonanginal     138   175
79    58    1  asymptomatic     150   270
278   57    1    nontypical     154   232
8     63    1  asymptomatic     130   254
115   41    1    nontypical     135   203
..   ...  ...           ...     ...   ...
269   42    1    nonanginal     130   180
266   52    1  asymptomatic     128   204
58    54    1    nonanginal     125   273
36    43    1  asymptomatic     120   177
192   43    1  asymptomatic     132   247

[76 rows x 5 columns]

In [16]:
Y_test

302     No
79     Yes
278    Yes
8      Yes
115     No
      ...
269     No
266    Yes
58      No
36     Yes
192    Yes
Name: AHD, Length: 76, dtype: object

In [24]:
dict={'Yes':0,'No':1}
update=data['AHD'].map(dict)
data['AHD'] = update
data

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,1
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,0
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,0
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,1
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,0
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,0
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,0
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,0
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,1