In [1]:
import pandas as pd

In [3]:
data=pd.read_csv(r"C:\Users\Admin\Downloads\Heart.csv")
data

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [4]:
df=data.iloc[:,1:]
df

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [5]:
dt=df.dtypes
dt

Age            int64
Sex            int64
ChestPain     object
RestBP         int64
Chol           int64
Fbs            int64
RestECG        int64
MaxHR          int64
ExAng          int64
Oldpeak      float64
Slope          int64
Ca           float64
Thal          object
AHD           object
dtype: object

In [6]:
avg=df['Age'].mean()
avg

54.43894389438944

In [7]:
miss=df.isnull()
miss

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [10]:
missing=df.isnull().sum()
missing

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         2
AHD          0
dtype: int64

In [11]:
shape=df.shape
shape

(303, 14)

In [12]:
df1=df[df==0]
df1.count()

Age            0
Sex           97
ChestPain      0
RestBP         0
Chol           0
Fbs          258
RestECG      151
MaxHR          0
ExAng        204
Oldpeak       99
Slope          0
Ca           176
Thal           0
AHD            0
dtype: int64

In [14]:
data1=df[['Age','Sex','ChestPain','RestBP',"Chol"]]
data1

     Age  Sex     ChestPain  RestBP  Chol
0     63    1       typical     145   233
1     67    1  asymptomatic     160   286
2     67    1  asymptomatic     120   229
3     37    1    nonanginal     130   250
4     41    0    nontypical     130   204
..   ...  ...           ...     ...   ...
298   45    1       typical     110   264
299   68    1  asymptomatic     144   193
300   57    1  asymptomatic     130   131
301   57    0    nontypical     130   236
302   38    1    nonanginal     138   175

[303 rows x 5 columns]

In [15]:
div75=df.sample(frac=0.75)
div25=df.drop(div75.index)
div75

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
53,44,1,nontypical,130,219,0,2,188,0,0.0,1,0.0,normal,No
159,68,1,nonanginal,118,277,0,0,151,0,1.0,1,1.0,reversable,No
244,60,0,nonanginal,120,178,1,0,96,0,0.0,1,0.0,normal,No
190,50,1,nonanginal,129,196,0,0,163,0,0.0,1,0.0,normal,No
103,71,0,nonanginal,110,265,1,2,130,0,0.0,1,1.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,61,1,asymptomatic,148,203,0,0,161,0,0.0,1,1.0,reversable,Yes
248,52,1,asymptomatic,125,212,0,0,168,0,1.0,1,2.0,reversable,Yes
82,39,1,nonanginal,140,321,0,2,182,0,0.0,1,0.0,normal,No
122,51,1,nonanginal,100,222,0,0,143,1,1.2,2,0.0,normal,No
110,61,0,asymptomatic,145,307,0,2,146,1,1.0,2,0.0,reversable,Yes

In [16]:
div25

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
8,63,1,asymptomatic,130,254,0,2,147,0,1.4,2,1.0,reversable,Yes
9,53,1,asymptomatic,140,203,1,2,155,1,3.1,3,0.0,reversable,Yes
13,44,1,nontypical,120,263,0,0,173,0,0.0,1,0.0,reversable,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,56,1,nontypical,120,240,0,0,169,0,0.0,3,0.0,normal,No
293,63,1,asymptomatic,140,187,0,2,144,1,4.0,1,2.0,reversable,Yes
298,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes

In [17]:
from sklearn.model_selection import train_test_split
x=df.iloc[:,:5]
y=df.iloc[:,13]
X_train,X_test,Y_train,Y_test=train_test_split(x,y,train_size=0.75,test_size=0.25)
X_train

     Age  Sex     ChestPain  RestBP  Chol
175   57    1  asymptomatic     152   274
65    60    1  asymptomatic     145   282
112   52    1       typical     118   186
66    60    1    nonanginal     140   185
93    44    0    nonanginal     108   141
..   ...  ...           ...     ...   ...
290   67    1    nonanginal     152   212
260   44    0    nonanginal     118   242
261   58    0    nontypical     136   319
144   58    1    nonanginal     105   240
139   51    1    nonanginal     125   245

[227 rows x 5 columns]

In [18]:
Y_train

175    Yes
65     Yes
112     No
66     Yes
93      No
      ...
290    Yes
260     No
261    Yes
144     No
139     No
Name: AHD, Length: 227, dtype: object

In [19]:
X_test

     Age  Sex     ChestPain  RestBP  Chol
101   34    1       typical     118   182
35    42    1  asymptomatic     140   226
134   43    0    nonanginal     122   213
57    41    1  asymptomatic     110   172
25    50    0    nonanginal     120   219
..   ...  ...           ...     ...   ...
145   47    1    nonanginal     108   243
92    62    1    nonanginal     130   231
103   71    0    nonanginal     110   265
177   56    1  asymptomatic     132   184
190   50    1    nonanginal     129   196

[76 rows x 5 columns]

In [20]:
Y_test

101     No
35      No
134     No
57     Yes
25      No
      ...
145    Yes
92      No
103     No
177    Yes
190     No
Name: AHD, Length: 76, dtype: object

In [21]:
data=data.replace({'Yes':0,'No':1})
data

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,1
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,0
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,0
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,1
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,0
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,0
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,0
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,0
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,1

In [22]:
dict={'Yes':0,'No':1}
update=data['AHD'].map(dict)
data['AHD']=update
data

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,NaN
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,NaN
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,NaN
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,NaN
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,NaN
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,NaN
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,NaN
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,NaN
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,NaN